name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_REF: mtelyxosqqaeadrrrtgk
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link to Supabase project
        run: supabase link --project-ref $PROJECT_REF
      
      - name: Push database migrations
        run: supabase db push
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      
      - name: Deploy extract-entities function
        run: supabase functions deploy extract-entities --project-ref $PROJECT_REF
      
      - name: Deploy generate-matches function
        run: supabase functions deploy generate-matches --project-ref $PROJECT_REF
      
      - name: Deploy generate-intro-email function
        run: supabase functions deploy generate-intro-email --project-ref $PROJECT_REF
